/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/access-keys/': RouteRecordInfo<
      '/access-keys/',
      '/access-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/access-keys/[id]': RouteRecordInfo<
      '/access-keys/[id]',
      '/access-keys/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin-tokens/': RouteRecordInfo<
      '/admin-tokens/',
      '/admin-tokens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin-tokens/[id]': RouteRecordInfo<
      '/admin-tokens/[id]',
      '/admin-tokens/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/buckets/': RouteRecordInfo<
      '/buckets/',
      '/buckets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/buckets/[id]': RouteRecordInfo<
      '/buckets/[id]',
      '/buckets/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/layout/': RouteRecordInfo<
      '/layout/',
      '/layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nodes': RouteRecordInfo<
      '/nodes',
      '/nodes',
      Record<never, never>,
      Record<never, never>,
      | '/nodes/[id]'
    >,
    '/nodes/[id]': RouteRecordInfo<
      '/nodes/[id]',
      '/nodes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/access-keys/index.vue': {
      routes:
        | '/access-keys/'
      views:
        | never
    }
    'src/pages/access-keys/[id].vue': {
      routes:
        | '/access-keys/[id]'
      views:
        | never
    }
    'src/pages/admin-tokens/index.vue': {
      routes:
        | '/admin-tokens/'
      views:
        | never
    }
    'src/pages/admin-tokens/[id].vue': {
      routes:
        | '/admin-tokens/[id]'
      views:
        | never
    }
    'src/pages/buckets/index.vue': {
      routes:
        | '/buckets/'
      views:
        | never
    }
    'src/pages/buckets/[id].vue': {
      routes:
        | '/buckets/[id]'
      views:
        | never
    }
    'src/pages/layout/index.vue': {
      routes:
        | '/layout/'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/nodes.vue': {
      routes:
        | '/nodes'
        | '/nodes/[id]'
      views:
        | 'default'
    }
    'src/pages/nodes/[id].vue': {
      routes:
        | '/nodes/[id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
